name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'homebrew/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'homebrew/**'

jobs:
  build-and-test:
    runs-on: macos-latest

    strategy:
      matrix:
        swift: ["5.9"]
        xcode: ["15.0"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}

    - name: Swift version
      run: swift --version

    - name: Build Debug
      run: swift build -v

    - name: Build Release
      run: swift build -c release -v

    - name: Build Universal Binary
      run: |
        swift build -c release --arch arm64 --arch x86_64

    - name: Verify Binary
      run: |
        file .build/apple/Products/Release/BigNotify
        lipo -info .build/apple/Products/Release/BigNotify

    - name: Test App Bundle Creation
      run: |
        # Create a minimal app bundle to test
        APP_DIR="test_build/BigNotify.app"
        mkdir -p "$APP_DIR/Contents/MacOS"
        mkdir -p "$APP_DIR/Contents/Resources"

        cp .build/apple/Products/Release/BigNotify "$APP_DIR/Contents/MacOS/"

        # Create Info.plist
        cat > "$APP_DIR/Contents/Info.plist" << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>BigNotify</string>
            <key>CFBundleIdentifier</key>
            <string>com.bignotify.app</string>
            <key>LSUIElement</key>
            <true/>
        </dict>
        </plist>
        EOF

        # Verify the app bundle structure
        ls -la "$APP_DIR/Contents/"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bignotify-binary
        path: .build/apple/Products/Release/BigNotify